# Data Consistency and Standardization

Real-world datasets often contain inconsistencies such as different text formats, extra spaces, special characters, and features with different numerical scales.

Data consistency ensures that all data follows a uniform format, while standardization and scaling prepare numerical features for Machine Learning algorithms.

In this section, we will perform:

- Text Data Cleaning
- Numerical Data Scaling
- Feature Transformation

# Text Data Cleaning

Text data frequently contains inconsistencies such as uppercase and lowercase letters, extra spaces, special characters, and spelling mistakes.

Cleaning text data improves data quality and ensures consistency throughout the dataset.

## Lowercase Conversion

Converting text to lowercase ensures that values with different letter cases are treated as the same value.

Example:

- "Male"
- "male"
- "MALE"

After conversion:

- "male"

In [90]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [91]:
df = sns.load_dataset("titanic")

In [92]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [93]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [94]:
df["Class"] = df["class"].str.lower()
df["Class"].head()

0    third
1    first
2    third
3    first
4    third
Name: Class, dtype: object

In [95]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Class
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,third
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,first
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,third
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,first
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,third

## Remove Extra Whitespaces

Leading and trailing spaces may cause duplicate values during analysis.

The `strip()` function removes unnecessary spaces.

- Example : "  Alisha Sajjad  " -> "Alisha Sajjad"

In [96]:
df["Class"] = df["class"].str.strip()

df["Class"].head()

0    Third
1    First
2    Third
3    First
4    Third
Name: Class, dtype: object

## Remove Special Characters

Special characters are often unnecessary for Machine Learning tasks.

Removing them creates cleaner and more consistent text data.

- Example -> "alisha@sajjad" → "alishasajjad"

In [97]:
import re 

df["Class"] = df["Class"].apply(lambda x: re.sub(r"[^a-zA-Z\s]", "", x))

df["Class"].head()

0    Third
1    First
2    Third
3    First
4    Third
Name: Class, dtype: str

## Unicode Normalization

Unicode normalization converts accented characters into standard English characters.

Example:

- café → cafe
- résumé → resume

In [98]:
import unicodedata

def normalize_text(text):
    return unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")

df["Class"] = df["Class"].apply(normalize_text)

df["Class"].head()

0    Third
1    First
2    Third
3    First
4    Third
Name: Class, dtype: str

## Spelling Correction

Some NLP applications require correcting spelling mistakes before analysis.

This technique is mainly used in Natural Language Processing (NLP).

In [99]:
%pip install textblob

Requirement already satisfied: textblob in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from textblob) (3.10.0)
Requirement already satisfied: defusedxml in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (0.7.1)
Requirement already satisfied: click in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (2026.7.19)
Requirement already satisfied: tqdm in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (4.69.1)
Requirement already satisfied: colorama in c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [87]:
from textblob import TextBlob 

df["Class"] = df["class"].apply(lambda x: str(TextBlob(x).correct()))

df["Class"].head()

0    Third
1    First
2    Third
3    First
4    Third
Name: Class, dtype: category
Categories (3, str): ['First', 'Second', 'Third']

# Numerical Data Standardization

Many Machine Learning algorithms perform better when numerical features are on a similar scale.

Scaling prevents features with larger values from dominating those with smaller values.

## Min-Max Scaling

Min-Max Scaling transforms numerical values into a range between **0 and 1**.

It is useful when the data does not contain significant outliers.

In [107]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df["Fare_MinMax"] = scaler.fit_transform(df[["fare"]])

df[["fare", "Fare_MinMax"]].head()

      fare  Fare_MinMax
0   7.2500     0.014151
1  71.2833     0.139136
2   7.9250     0.015469
3  53.1000     0.103644
4   8.0500     0.015713

## Standard Scaling (Z-Score)

Standard Scaling transforms data so that:

- Mean = 0
- Standard Deviation = 1

It is commonly used when the data approximately follows a normal distribution.

In [108]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df["Fare_Standard"] = scaler.fit_transform(df[["fare"]])

df[["fare", "Fare_Standard"]].head()

      fare  Fare_Standard
0   7.2500      -0.502445
1  71.2833       0.786845
2   7.9250      -0.488854
3  53.1000       0.420730
4   8.0500      -0.486337

## Robust Scaling

Robust Scaling uses the median and interquartile range (IQR) instead of the mean and standard deviation.

It is particularly useful when the dataset contains many outliers.

In [109]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

df["Fare_Robust"] = scaler.fit_transform(df[["fare"]])

df[["fare", "Fare_Robust"]].head()

      fare  Fare_Robust
0   7.2500    -0.312011
1  71.2833     2.461242
2   7.9250    -0.282777
3  53.1000     1.673732
4   8.0500    -0.277363

## Log Transformation

Log Transformation reduces skewness and minimizes the influence of large values.

It is commonly applied to highly skewed numerical features.

In [110]:
import numpy as np 

df["Fare_Log"] = np.log1p(df["fare"])

df[["fare", "Fare_Log"]].head()

      fare  Fare_Log
0   7.2500  2.110213
1  71.2833  4.280593
2   7.9250  2.188856
3  53.1000  3.990834
4   8.0500  2.202765

## Power Transformation

Power Transformation makes data more normally distributed and reduces skewness.

It is useful for improving the performance of certain Machine Learning algorithms.

In [111]:
from sklearn.preprocessing import PowerTransformer

scaler = PowerTransformer()

df["Fare_Power"] = scaler.fit_transform(df[["fare"]])

df[["fare", "Fare_Power"]].head()

      fare  Fare_Power
0   7.2500   -0.878820
1  71.2833    1.336651
2   7.9250   -0.790065
3  53.1000    1.067352
4   8.0500   -0.774439

## 📌 Key Points to Remember

- **Text Cleaning:** Converting text to lowercase, removing extra spaces, and correcting spelling mistakes help maintain consistency in textual data.

- **Numeric Scaling:** Standardization and transformation techniques normalize feature ranges and improve data distribution for Machine Learning algorithms.

- **Model Compatibility:** Clean, consistent, and properly scaled data enables Machine Learning models to learn more effectively, resulting in better performance and more accurate predictions.

---

> **📝 Note:** A well-preprocessed dataset improves data quality, enhances model performance, and leads to more accurate and reliable Machine Learning predictions.